### ISSUE TITLE
sni-nomatch-abort option is ignored

### ISSUE THREAD

**Issue by vovcacik** [varnish/hitch#121]
Hi, I have `sni-nomatch-abort` enabled, but according to ssllabs.com some clients (e.g. Android 2.3.7) that don't support SNI connected to the server.
## My config:

```
frontend="[*]:443"
backend="[::1]:80"

ciphers="AES256+EECDH:AES256+EDH:AES128+EDH"
prefer-server-ciphers="on"

pem-file="/var/lib/acme/live/nano.ovcacik.org/haproxy"

ocsp-dir="/var/lib/hitch-ocsp"
ocsp-verify-staple="on"

sni-nomatch-abort="on"

alpn-protos="http/1.1"
```
## The analysis:

https://www.ssllabs.com/ssltest/analyze.html?d=nano.ovcacik.org

**Comment by lkarsten** [comment]
Hi. Sorry for taking so long to get back to you.

Rerunning the ssllabs test, I don't see this happening any more. This is probably because you've changed ciphers and/or TLS version so that the old clients are not compatible any longer.

`sni-nomatch-abort` works only for SNI enabled clients. If the client doesn't support it, the default Hitch frontend is used. I don't think this is very common any longer.

**Comment by vovcacik** [comment]
In that case it worked as expected. Thanks for clarification.
