### ISSUE TITLE
Need sys/filio on SunOS for FIONBIO

### ISSUE THREAD

**Issue by bahamat** [varnish/hitch#146]
In order to compile on SunOS (illumos or Solaris), sys/filio is needed.

**Comment by Dridi** [comment]
I tried to compile hitch on SmartOS but I could only get libev without development files. I was hoping to be able to do this quickly but I can try again later.

**Comment by mamash** [comment]
Userland packages on SmartOS come from pkgsrc, which always includes headers with packages. The libev package contains both the headers and the shared lib.

**Comment by Dridi** [comment]
Hello, sorry for the delay, I will have another look.

**Comment by Dridi** [comment]
It's been a painful process but I have finally merged #147 today. After @mamash's comment I had requested some help and got my head around `pkgin` but the real problem is that libev is distributed without a `pkgconfig` file which is needed by our `autoconf` script. It doesn't seem to be the case, even for the latest version of libev packaged for SmartOS as of today. If you are a SmartOS user, please get in touch with them to improve libev packaging, we are primarily Linux users.

I ran into other problems trying to manually detect libev, tripped a couple time on deceptive paths but was eventually able to reproduce the `FIONBIO` problem and confirm that the patch fixes it. There are portability issues with our current build system and I will personally fix them, and then I'll try to figure out why a test case failed on SmartOS. This is not going to happen until I also squash #73.

Thank you for your patience, you should be able to build the current master on SunOS/SmartOS.

**Comment by mamash** [comment]
I hear you, but the libev upstream themselves do not provide a pkg-config file, and the pkgsrc community traditionally respects the upstream position and won't inject its own file like this; we at pkgsrc will rather help the hitch package overcome any obstacles it encounters at configure time. A simple configure path arg is often found more reliable than any per-OS path guessing.

Anyway, thanks for the fix here, it's one patch less for us to carry.

**Comment by Dridi** [comment]
Actually even on my Fedora system there's no `libev.pc`, so I probably distracted by the other portability issues. After I fix them I will double-check libev detection.

**Comment by Dridi** [comment]
@bahamat, @mamash, #163 should build out of the box on SmartOS with GCC (if I remove -Werror it also compiles with SunCC). Can you give it a try and let me know whether it also works for you without having to pass more than one `-I` flag and one `-L` flag for libev?

Bonus question: do all the tests pass for you?

Thanks!

PS. no worries if you can't
