### ISSUE TITLE
Hitch error between HA-Proxy 1.6.10 and Varnish

### ISSUE THREAD

**Issue by jasonpursian** [varnish/hitch#148]
Hello,

I've compiled Hitch 1.4.3 on an Ubuntu 16.04 LTS server, and am receiving an error when connecting from the HA-Proxy box in front of it. No connections make it to Varnish, sitting behind Hitch.

Detail error:

172.31.45.168:53642 :0 10:11 Handshake failure: error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol

What I'm trying to accomplish is providing HTTP/2 support in this stack, but even with it hashed out on HA-Proxy and Hitch configurations, I still receive the same error.

HA-Proxy -- Hitch -- Varnish5 -- Apache

Thanks for any tips!

**Comment by jasonpursian** [comment]
hitch.conf:

# Run 'man hitch.conf' for a description of all options.

frontend = "[*]:443"
backend = "[::1]:6086"    # 6086 is the default Varnish PROXY port.
alpn-protos = "h2,http/1.1" # Enable to let clients negotiate HTTP/2 with ALPN. (default off)
pem-file = "/etc/ssl/pems/munin.pem" # Would be nice to specify a directory instead...

tls-protos = TLSv1.1 TLSv1.2
ciphers = "ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!3DES:!MD5:!PSK"

prefer-server-ciphers = on
workers = 1                     # number of CPU cores

daemon = on
user = "hitch"
group = "hitch"

write-proxy = on             # Write PROXY header

**Comment by gquintard** [comment]
Very stupid question, why are you even using Hitch?  :-)

On Dec 15, 2016 21:07, "jasonpursian" <notifications@github.com> wrote:

Hello,

I've compiled Hitch 1.4.3 on an Ubuntu 16.04 LTS server, and am receiving
an error when connecting from the HA-Proxy box in front of it. No
connections make it to Varnish, sitting behind Hitch.

Detail:

172.31.45.168:53642 :0 10:11 Handshake failure: error:140760FC:SSL
routines:SSL23_GET_CLIENT_HELLO:unknown protocol

What I'm trying to accomplish is providing HTTP/2 support in this stack,
but even with it hashed out on HA-Proxy and Hitch configurations, I still
receive the same error.

HA-Proxy -- Hitch -- Varnish5 -- Apache

Thanks for any tips!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/varnish/hitch/issues/148>, or mute the thread

**Comment by jasonpursian** [comment]
haproxy.cfg:

global
        log /dev/log    local0
        log /dev/log    local1 notice
        chroot /var/lib/haproxy
        stats socket /run/haproxy/admin.sock mode 660 level admin
        stats timeout 30s
        user haproxy
        group haproxy
        daemon
        maxconn 2048
        tune.ssl.default-dh-param 2048

        # Default SSL material locations
        ca-base /etc/ssl/certs
        crt-base /etc/ssl/private

        # Default ciphers to use on SSL-enabled listening sockets.
        # For more information, see ciphers(1SSL). This list is from:
        #  https://hynek.me/articles/hardening-your-web-servers-ssl-ciphers/

        ssl-default-bind-ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!3DES:!MD5:!PSK
        ssl-default-bind-options no-sslv3

        ssl-default-server-options no-sslv3
       ssl-default-server-ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!3DES:!MD5:!PSK

defaults
        log     global
        mode    http
        option  httplog
        option  dontlognull
        option  forwardfor
        option  http-server-close
        timeout http-request 5s # prevent open connections
        timeout connect 5000
        timeout client  50000
        timeout server  50000
        errorfile 400 /etc/haproxy/errors/400.http
        errorfile 403 /etc/haproxy/errors/403.http
        errorfile 408 /etc/haproxy/errors/408.http
        errorfile 500 /etc/haproxy/errors/500.http
        errorfile 502 /etc/haproxy/errors/502.http
        errorfile 503 /etc/haproxy/errors/503.http
        errorfile 504 /etc/haproxy/errors/504.http

listen stats
        bind :9600
        mode http
        stats enable
        stats hide-version
        stats realm Haproxy\ Statistics
        stats uri /haproxy?stats
        stats auth u:p
        stats admin if TRUE #allows to up/down servers

frontend http-in
        mode tcp
        bind *:80
        bind *:443 ssl crt /etc/ssl/pems/ alpn h2,http/1.1
        acl secure dst_port eq 443
        redirect scheme https code 301 if !{ ssl_fc }
        
        use_backend varnish if { ssl_fc_alpn -i h2 } # set a backend for http/2
        default_backend varnish # backend for dynamic content

backend varnish
        mode tcp
        balance roundrobin
        option tcp-check
        default-server inter 5s fall 3 rise 2

        server 172.31.38.12 172.31.38.12:443 check send-proxy

**Comment by jasonpursian** [comment]
> Very stupid question, why are you even using Hitch?  :-)

Not at all a stupid question! I asked myself the same thing when starting on this. Why add another moving part?? I have a fine, functional stack w/o Hitch in production, and had a request out from our web development team to start supporting HTTP/2.

We're running high availability WordPress in AWS.

Our current production stack is HTTPS only, with HA-Proxy doing termination in http mode, sending on to Varnish4, and from there to Apache. We're able to cache select HTTPS requests using Varnish, which works very well.

Well, to support HTTP/2, I have to make some changes. HA-Proxy doesn't terminate in tcp mode (yet), and h2 doesn't work in http mode, so I need a terminator in front of Varnish. I read up on Hitch, and decided to try it.

**Comment by gquintard** [comment]
Another stupid question: isn't HAProxy sending cleartext while Hitch expects SSL/TLS?

**Comment by lukastribus** [comment]
> HA-Proxy doesn't terminate in tcp mode (yet), and h2 doesn't work in http mode, so I need a terminator in front of Varnish.

Wrong! Haproxy terminates SSL in TCP mode just fine, and that is exactly how you configured Haproxy here.


> Another stupid question: isn't HAProxy sending cleartext while Hitch expects SSL/TLS?

And that is the problem here exactly. Haproxy decrypts TLS and sends cleartext to Hitch, with again expects TLS.

You have to decrypt TLS ONCE, and install certificates ONCE. If you are doing it twice, you are doing it wrong.

**Comment by gquintard** [comment]
Thanks Lukas, I'm far from being a HAProxy expert, so that helps a lot.

Jason, can I attract your intention to the proxy-proxy parameter in Hitch?
That will allow HAProxy to use the PROXY protocol, and Hitch to simply
relay it dumbly to Varnish. That seems to be the less cumbersome setup if
you want to keep Hitch in the picture.

-- 
Guillaume Quintard

**Comment by gquintard** [comment]
@jasonpursian any luck with the proxy-proxy parameter?

**Comment by gquintard** [comment]
sorry, meant to tag @lukastribus ...

**Comment by lukastribus** [comment]
I think you meant to tag the OP, which is in fact Jason.

**Comment by gquintard** [comment]
Erf, I was right the first time, sorry for poking you.

**Comment by Cactusbone** [comment]
I'm also interested in proxy-proxy, to be able to use HAProxy for loadbalancing, and hitch for ssl.

**Comment by lukastribus** [comment]
And although it doesn't make sense, nothing stops you. Just configure it appropriately.

This is issue should be closed, as the OP simply configured it wrong.

**Comment by Cactusbone** [comment]
How ? I could not find it in any docs ? Configuring a haproxy with working http/2 is more work than using hitch directly, since alpn support is not included in default haproxy (not in the official docker image at least)

**Comment by lukastribus** [comment]
How what exactly?

The issue of the OP is wrong configuration, as he sends cleartext traffic to a TLS port. Once he corrects his setup, it will work fine (either disable TLS termination on haproxy, or disable TLS termination on hitch, or enable TLS encryption on the haproxy backend). The setup still doesn't make sense, but it will work fine.

This setup doesn't make sense because Hitch and Haproxy are doing the same thing. Either drop Hitch, or drop haproxy from the mix.

Every released version of haproxy that supports TLS (> 1.5), also supports ALPN. Of course OpenSSL has to support ALPN as well, so OpenSSL 1.0.2 is required for this, which is exactly the same requirement Hitch has.

**Comment by Cactusbone** [comment]
Ha ok, yeah i see the point, indeed the bug is about the conf. I was asking about hitch accepting proxy protocol from upstream proxy, and I don't think that's implemented, but anyway, just use haproxy for that, and not hitch :) got it :) thanks .

**Comment by jasonpursian** [comment]
Yeah I've moved on from using hitch. As @lukastribus noted I was doing it wrong. Closing.
