### ISSUE TITLE
Can not use h2 with hitch on centos

### ISSUE THREAD

**Issue by amro80** [varnish/hitch#150]
I get warning when reload hitch with ALPN protoco enabled with  "h2/http1.1" as per the documentation. I am on hitch 1.4.3.

Warning: "{npn} Warning: Hitch has been compiled against a version of OpenSSL without ALPN support."

#yum info openssl
Loaded plugins: fastestmirror, security
Loading mirror speeds from cached hostfile
 * base: mirror.keystealth.org
 * epel: mirror.sjc02.svwh.net
 * extras: mirrors.kernel.org
 * updates: centos.unixheads.org
Installed Packages
Name        : openssl
Arch        : x86_64
Version     : 1.0.1e
Release     : 48.el6_8.3
Size        : 4.0 M
Repo        : installed
From repo   : updates
Summary     : A general purpose cryptography library with TLS implementation
URL         : http://www.openssl.org/
License     : OpenSSL
Description : The OpenSSL toolkit provides support for secure communications between
            : machines. OpenSSL includes a certificate management tool and shared
            : libraries which provide various cryptographic algorithms and
            : protocols.

Available Packages
Name        : openssl
Arch        : i686
Version     : 1.0.1e
Release     : 48.el6_8.3
Size        : 1.5 M
Repo        : updates
Summary     : A general purpose cryptography library with TLS implementation
URL         : http://www.openssl.org/
License     : OpenSSL
Description : The OpenSSL toolkit provides support for secure communications between
            : machines. OpenSSL includes a certificate management tool and shared
            : libraries which provide various cryptographic algorithms and
            : protocols.

**Comment by hermunn** [comment]
ALPN support was introduced with OpenSSL 1.0.2. Most browsers will only speak HTTP2 if negotiated with ALPN, and your OpenSSL version does not support ALPN.

Hitch sees that ALPN is not available, and writes the warning. I do not think this is a bug.

Furthermore, note that "h2/http1.1" is not a good string for specifying the ALPN protocols - it should be a comma separated list of protocols. Please read the hitch manual (`man hitch` and/or `man hitch.conf`) for more details.

**Comment by amro80** [comment]
Hi All,

any ideas?

Amro

**Comment by hermunn** [comment]
Back at work now.

It looks like hitch is compiled with header files from OpenSSL 1.0.2, but tries to link with an SSL without the functions `SSL_get0_alpn_selected` and `SSL_CTX_set_alpn_select_cb`. This means that the command that fails tries to link with the wrong OpenSSL library or that the version you have was compiled without ALPN support (unlikely).

It might be possible to change the failing command (`gcc -O2 -g -std=c99 -fno-strict-aliasing -Wall -W -D_GNU_SOURCE -g -O2 -o hitch configuration.o ringbuffer.o hitch.o cfg_parser.o cfg_lex.o hssl_locks.o asn_gentm.o ocsp.o logging.o foreign/vpf.o foreign/flopen.o foreign/vas.o foreign/vsb.o -L/usr/local/ssl/lib64 -lssl -L/usr/local/ssl/lib64 -lcrypto -lev -lrt hitch.o`) so that it links with the correct library. This can be tried manually, in the directory `/usr/src/hitch-1.4.3/src` in your case. I am guessing that `-lssl` picks the old version of OpenSSL, and that removing `-lssl` in favor of something like `/usr/local/ssl/lib64/libssl.a` (without `-l`, in the same location, since the linker is single pass) will work.

**Comment by amro80** [comment]
>  This means that the command that fails, tries to link with the wrong OpenSSL library, or that the version you have was compiled without ALPN support (unlikely).

**Comment by amro80** [comment]
sorry closed it by mistake. I still need your advice about my last comment.

Amro

**Comment by daghf** [comment]
Hey @amro80 

Hitch is packaged in EPEL, so you should be able to install from packages without needing to build it yourself on CentOS.

Please have a look at https://github.com/varnish/hitch/blob/master/docs/configuration.md#alpnnpn-support for information on how to enable ALPN/NPN.

Note that Hitch will do ALPN/NPN negotiation, however it does not implement the H/2 protocol bits itself. If you negotiate H/2 in Hitch, the backend configured needs to be able to handle clear text H/2 (h2c) for this to work.
