### ISSUE TITLE
tls-protos seams not to work in frontend section

### ISSUE THREAD

**Issue by HLeithner** [varnish/hitch#159]
It seams that tls-protos is not used or at least doesn't override global tls-protos setting.

```
tls-protos = TLSv1.0 TLSv1.1 TLSv1.2

frontend = {
  host = "ip"
  port = "443"
  pem-file = "/etc/hitch/certs/xxx.pem"
  tls-protos = TLSv1.2
}```

Seams not to limit TLS to version 1.2 reported by ssllabs.

**Comment by daghf** [comment]
Hi

I tried to reproduce this with a minimal config similar to yours, and it seems to work as intended:

```
tls-protos = TLSv1.0 TLSv1.1 TLSv1.2

backend = "[localhost]:8080"

frontend = {
  host = "127.0.0.1"
  port = "9443"
  pem-file = "src/tests/certs/site1.example.com"
  tls-protos = TLSv1.2
}


frontend = {
  host = "127.0.0.1"
  port = "8443"
  pem-file = "src/tests/certs/site2.example.com"
}

frontend = {
  host = "127.0.0.1"
  port = "7443"
  pem-file = "src/tests/certs/site3.example.com"
}
```

By simple testing via `openssl s_client` all endpoints present the correct certificates, and the `:9443` endpoint only permits `TLSv1.2` handshakes (shuts down with `unsupported protocol` for anything else).

What happens when you do `openssl s_client -connect ip:443 -tls1_1` for the endpoint you have configured as `TLSv1.2`?

**Comment by HLeithner** [comment]
Hmm maybe I missed a restart or so I will retest on monday.

**Comment by HLeithner** [comment]
Ok sorry was my fault seams to work fine I my missed a restart.
