### ISSUE TITLE
Zombie processes on -HUP

### ISSUE THREAD

**Issue by jpotter** [varnish/hitch#167]
Hi,

I'm noticing on hitch 1.4.4 on CentOS 7 that hitch doesn't correctly clean up prior processes went sent a -HUP.

I.e., before:

```# ps auxw | grep hitch
root     30483  0.0  1.1  57748 11224 ?        Ss   00:16   0:00 /usr/sbin/hitch --pidfile=/run/hitch/hitch.pid --config=/etc/hitch/hitch.conf
hitch    30484  0.0  1.1  57748 11476 ?        S    00:16   0:00 /usr/sbin/hitch --pidfile=/run/hitch/hitch.pid --config=/etc/hitch/hitch.conf
hitch    30485  0.0  1.1  57748 11480 ?        S    00:16   0:00 /usr/sbin/hitch --pidfile=/run/hitch/hitch.pid --config=/etc/hitch/hitch.conf
```

Then after `kill -HUP 30483`, we have a defunct process:

```
root     30483  0.6  2.1  67116 21724 ?        Ss   00:16   0:00 /usr/sbin/hitch --pidfile=/run/hitch/hitch.pid --config=/etc/hitch/hitch.conf
hitch    30485  0.0  0.0      0     0 ?        Z    00:16   0:00 [hitch] <defunct>
hitch    30488  0.0  2.0  67116 20804 ?        S    00:16   0:00 /usr/sbin/hitch --pidfile=/run/hitch/hitch.pid --config=/etc/hitch/hitch.conf
hitch    30489  0.0  2.0  67116 20952 ?        S    00:16   0:00 /usr/sbin/hitch --pidfile=/run/hitch/hitch.pid --config=/etc/hitch/hitch.conf
```

This ends up stacking up over time, i.e. each reload of hitch causes another zombie process to stay around:

```
# ps auxw | grep Z
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
hitch    13630  0.0  0.0      0     0 ?        Z    Feb10   0:00 [hitch] <defunct>
hitch    15272  0.0  0.0      0     0 ?        Z    Feb10   0:00 [hitch] <defunct>
hitch    15444  0.0  0.0      0     0 ?        Z    Feb10   0:00 [hitch] <defunct>
hitch    15495  0.0  0.0      0     0 ?        Z    Feb10   0:00 [hitch] <defunct>
hitch    29346  0.0  0.0      0     0 ?        Z    00:06   0:00 [hitch] <defunct>
hitch    29597  0.0  0.0      0     0 ?        Z    00:07   0:00 [hitch] <defunct>
```

**Comment by dward** [comment]
I noticed the same thing. On reconfigure, hitch kills the ocsp worker, and then starts a new one. By the time do_wait() is called, ocsp_proc_pid has the new worker pid, instead of the one that should be cleaned up.

I'm currently testing the removal of start_ocsp_proc(); from reconfigure and letting do_wait() do it's job once it receives a SIGCHLD for the kill.

**Comment by bago** [comment]
I'm on Centos7 and I use kill -HUP for hot reloading of certificates (well, in fact I switched from pound to hitch mainly for this great feature).

I can confirm that since upgrading to hitch-1.4.4-2.el7.x86_64 I started seeing defunct processes. Previously I was on hitch-1.4.1-1.el7.x86_64 and never had defuct processes.
