### ISSUE TITLE
Hitch error : {backend} Socket error: Connection reset by peer

### ISSUE THREAD

**Issue by colas31** [varnish/hitch#171]
Hello,

I have compiled Hitch 1.4.4 and using Varnish 4.1.5

When I start Hitch I get this message in my syslog, I just give it in case it could be the source of my problem.
`{npn} Warning: Hitch has been compiled against a version of OpenSSL without ALPN support.`

A user complains that the webiste isn't displaying with Chrome And Firefox, and get this error : 
`ERR_SPDY_PROTOCOL_ERROR`

In my syslog I get this error from Hitch :` {backend} Socket error: Connection reset by peer`

There the varnishlog : 
```
*   << Request  >> 98317
-   Begin          req 98316 rxreq
-   Timestamp      Start: 1488201993.222717 0.000000 0.000000
-   Timestamp      Req: 1488201993.222717 0.000000 0.000000
-   HttpGarbage    "PRI%00"
-   ReqAcct        18 0 18 28 0 28
-   End

*   << Session  >> 98316
-   Begin          sess 0 PROXY
-   SessOpen       127.0.0.1 51414 127.0.0.1:8443 127.0.0.1 8443 1488201993.221726 24
-   Proxy          2 xx.xxx.xx.xx 2143 xx.xx.xx.xx 443
-   Link           req 98317 rxreq
-   SessClose      RX_JUNK 0.001
-   End
```

If I witch with nginx this same user can access to the website.

My hitch config : 
```
# Listening
frontend = "[*]:443"
ciphers  = "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH"

backend = "[127.0.0.1]:8443"

workers = 4
write-proxy-v2 = on

alpn-protos = "http/2, http/1.1"
ocsp-verify-staple = on
alpn-protos = "h2,http/1.1"
tls-protos = TLSv1.0 TLSv1.1 TLSv1.2 SSLv3

pem-file = "/etc/hitch/tutoandco.pem"

daemon = on
user = "nobody"
group = "nogroup"
```

In my syslog, I encounter this error to multiple times

Thanks for help

**Comment by hermunn** [comment]
This is not a bug. You have configured hitch to negotiate HTTP 2, but varnish 4.1.5 does not support it. You should use

```
alpn-protos = "http/1.1"
```
and switch back to your current setting when you start using a varnish version with good HTTP 2 support. Varnish 5.1 is not yet released, but you can check out the latest development version (https://github.com/varnishcache/varnish-cache) now if you want to test HTTP 2 in varnish.

However, as the warning says, you need a recent OpenSSL version for ALPN, and recent web browsers will not use HTTP 2 without ALPN negotiation. Because of this, you will probably also want to update your setup to a more recent version of your distribution before you can test HTTP 2 properly.

**Comment by colas31** [comment]
Thank you for the explanation. I misunderstood the HTTP 2 and probably don't read carefully the documentation.

I can't explain why with the same browser version on two different computer, only one got the problems.

Regarding the version of OpenSSL, I have this one OpenSSL 1.0.1t  3 May 2016 and it's the lastest I can get from the repo. :/
