### ISSUE TITLE
Hitch not restarting on boot CentOS7

### ISSUE THREAD

**Issue by MikeParkin** [varnish/hitch#188]
I know this is not the 'correct' channel for this, as it is a CentOS7 bug, but I thought good to leave a note for it. For my install hitch was starting successfully but not after a server reboot. This came down to the /usr/lib/systemd/system/hitch.service file having Type=simple, to fix it I changed to 

Type=forking

And also added this line:

PIDFile=/run/hitch/hitch.pid

**Comment by denisbr** [comment]
@MikeParkin Is this issue still relevant with the latest version of the package and it's systemd unit?

**Comment by MikeParkin** [comment]
@denisbr the latest version still has Type=simple, so yes I believe so.

**Comment by denisbr** [comment]
@MikeParkin did you try?

**Comment by denisbr** [comment]
@ingvarha I've verified this in the latest EPEL package, and I've cross-checked with our Varnish Plus package, which has been using "Forking" from the start.

**Comment by denisbr** [comment]
I'll close this ticket, as this is not the correct place for it. Please file an issue over at https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora+EPEL

**Comment by gquintard** [comment]
@MikeParkin : regardless of the channel, isn't keeping "simple" and running hitch as foreground a better approach?

**Comment by MikeParkin** [comment]
Sorry I forgot to mention I did raise this as a bug report on the redhat bug tracker. Only just seen that @ingvarha has replied there (I didn't get a notification). 

@gquintard perhaps it is, however that didn't allow hitch to reboot after a restart in my case. I'll try and pull together some information and update the bug report on Redhat.

https://bugzilla.redhat.com/show_bug.cgi?id=1467839

**Comment by Thue** [comment]
Just to summarize the conclusion from the Red Hat bug report here:

hitch.conf has a setting "daemon = on/off". If you set "daemon=on", then the hitch.service needs to set "Type=forking", since the hitch process will fork off a daemon. If you set "daemon=off", then you need to set "Type=simple". "daemon=off"+"Type=simple" is the most elegant and standard solution.

If you set "daemon=on" and "Type=simple", then hitch will fork and the original process will exit with a non-error exit status. I assume that Systemd will then detect that the started service has exited, which since "Type=simple" means that the service has ended, and systemd then presumably cleans up any stray child processes. Stray child processes here then includes the hitch deamon which was forked.

The Red Hat/CentOS packages has hitch.conf and hitch.service correctly configured. Problems seem to happen when people mindlessly copy a complete hitch configuration file with "deamon=on" and use that on a centos system.

**Comment by gquintard** [comment]
Just needed to comment on this:

> "daemon=off"+"Type=simple" is the most elegant and standard solution.

That's just not true. This combination makes you blind to startup errors, like a syntax error and will force you to wait a bit then check with `systemctl status` that `hitch` is still running.

`daemon=on`+`Type=forking` ensures that the process correctly fork and `systemctl [re]start` returns a meaningful code.

**Comment by Thue** [comment]
You are correct about that hidden startup errors.

I wonder why systemd doesn't e.g. wait 0.5 seconds to see if the process errors out. Or ideally the hitch process should have some way to communicate to systemd when the initialization phase has completed successfully, and systemd could then wait for that when running interactively.

**Comment by Thue** [comment]
I reported the missing reporting of errors during initialization, due to using Type=simple, to the Red Hat bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1731420
