### ISSUE TITLE
Hitch with OpenSSL1.1.1 support

### ISSUE THREAD

**Issue by wioxjk** [varnish/hitch#190]
Is there any plan to have OpenSSL1.1.1 support in order to utilize TLS1.3?

**Comment by lkarsten** [comment]
I'm interested in getting TLS 1.3 running with Hitch.

**Comment by lkarsten** [comment]
I've played around with this today.

To get hitch master to build with openssl master (there is no 1.1.1 yet), a trivial patch is required: https://github.com/lkarsten/hitch/commit/feb67119549125cbac78645c0f37fec6fc4aca9e .. Someone that knows OpenSSL (and C!) better than me should review that for unintended consequences.

To compile with a non-system openssl version, set the usual overrides:
```
#!/bin/bash -x
OPENSSL=$HOME/openssl-master
export PKG_CONFIG_LIB=${OPENSSL}/lib/pkgconfig/
export PKG_CONFIG_PATH=${OPENSSL}/lib/pkgconfig/
export LD_LIBRARY_PATH=${OPENSSL}/lib/
#export PATH=${OPENSSL}/bin:$PATH
```

`openssl s_client` 1.1.0f behaves a bit differently when it has openssl 1.1.1 as a library. The connections are described as TLS1.3 in the output, and some tests are failing because of that.

`openssl s_client` 1.1.1/master fails a lot.

To work around that, I'm setting rpath on the hitch binary and leaving PATH and LD_LIBRARY_PATH alone after compilation:
```
lkarsten@lima:~/work/hitch$ patchelf --set-rpath /home/lkarsten/openssl-master/lib/ src/hitch
warning: working around a Linux kernel bug by creating a hole of 1708032 bytes in ‘src/hitch’
lkarsten@lima:~/work/hitch$ ldd src/hitch
	linux-vdso.so.1 (0x00007ffe8ff31000)
	libssl.so.1.1 => /home/lkarsten/openssl-master/lib/libssl.so.1.1 (0x00007f6dbb6e2000)
	libcrypto.so.1.1 => /home/lkarsten/openssl-master/lib/libcrypto.so.1.1 (0x00007f6dbb206000)
	libev.so.4 => /usr/lib/x86_64-linux-gnu/libev.so.4 (0x00007f6dbafda000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6dbac3b000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f6dbaa37000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f6dba818000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f6dba514000)
	/lib64/ld-linux-x86-64.so.2 (0x0000560b9db7f000)
lkarsten@lima:~/work/hitch$
```

```
lkarsten@lima:~/work/hitch$ which openssl
/usr/bin/openssl
lkarsten@lima:~/work/hitch$ ldd /usr/bin/openssl
	linux-vdso.so.1 (0x00007ffe657d9000)
	libssl.so.1.1 => /usr/lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007f37dfc93000)
[..]
```
With this setup, all tests pass successfully.

**Comment by huiser** [comment]
OpenSSL 1.1.1 has been released, last September.
