### ISSUE TITLE
How does hitch score on SSL server test?

### ISSUE THREAD

**Issue by nodesocket** [varnish/hitch#23]
Can we get a link to a [SSL Server Test](https://www.ssllabs.com/ssltest/) using default hitch settings.

Thanks.

**Comment by ktk** [comment]
See #25, currently I get a B

**Comment by lkarsten** [comment]
Hi.

https://www.ssllabs.com/ssltest/analyze.html?d=hitch-tls.org reports A for me, using the documented configuration. (see docs/ in the build)

**Comment by gperciva** [comment]
Sorry for jumping in on a closed issue.  If you enable HTTP Strict Transport Security (HSTS), you get an A+ in ssllabs.

**Comment by ktk** [comment]
@gperciva can you paste the config?

**Comment by gperciva** [comment]
@kth sure, it's nothing fancy though!

```
frontend = "[*]:443"
backend = "[::1]:80"
user = "ec2-user"

# recommended ciphers from
# https://github.com/varnish/hitch/blob/master/docs/configuration.md
ciphers = "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH"
prefer-server-ciphers = on

pem-file = "wwwtest.tarsnap.net.pem"
```

That by itself gets an A.  To push it to A+, I added:

```
Header set Strict-Transport-Security "max-age=15552000; includeSubDomains; preload
```

to `.htaccess`.  Note, however, that the above line will set HSTS to **http** connections as well.  That's forbidden by the standard, but I haven't yet figured out how to restrict the header to only https connections.  If I was using apache to handle HTTPS, then I could add `env=HTTPS` to the end of that line, but since I'm using hitch for HTTPS, I'll need some other solution.  (I'm new to apache and web servers in general)

The A+ rating doesn't mean it's perfect.  I have 100% on the certificate, 95% on protocol support, and 90% on key exchange and cipher strength.  There's also a few red and orange marks in the in-depth report; "no SNI", "no FS", and "DH public server param (Ys) reuse".
https://www.ssllabs.com/ssltest/analyze.html?d=wwwtest.tarsnap.net
