### ISSUE TITLE
Feature: Connect to Backend Unix Domain Socket

### ISSUE THREAD

**Issue by josh4trunks** [varnish/hitch#257]
Varnish Cache, since version 6.0.0 can listen on a Unix domain socket (UDS), also know as a unix file socket. Other servers, like NGINX can also listen on a UDS.

I would make sense that Hitch could have `backend = /path/to/file.sock`. This avoids an additional TCP connetion on systems where Hitch is proxying TLS/SSL to a local server.

**Comment by josh4trunks** [comment]
@Dridi CCing you since you mentioned you may be willing to help here https://lists.gt.net/varnish/dev/42967#42967.

**Comment by Dridi** [comment]
Hello @josh4trunks,

The whole team has been following the progress of unix domain sockets in Varnish 6, and we are well aware of it since Hitch developers are also part of the Varnish core developers team. Hitch is a generic TLS proxy but was developed with Varnish in mind, so we'll get around to supporting it with no ETA (although we want this support sooner than later). I can at least confirm it will not be part of the next release.

I'm also closing this issue because we don't use the issue tracker for feature requests. I added an entry to the wiki in the future features page.

https://github.com/varnish/hitch/wiki/Future-features

Dridi

**Comment by dkrieger** [comment]
I'd just like to add that supporting unix domain sockets would really make this a great local TLS terminator option for websockets. I'd rather not use HAProxy for that as it seems a bit like pushing in a thumbtack with a sledgehammer, but that seems to be the only viable option remaining.

**Comment by alexshpilkin** [comment]
@Dridi Am I correct in saying that domain socket backends are already in master? At least `hitch.c` [seems to have][1] everything in place.

[1]: https://github.com/varnish/hitch/blob/372f3559c720ab598ae0360d1c1696c7b8189e4b/src/hitch.c#L2932

**Comment by alexshpilkin** [comment]
Specifically, commit 730740260679132af277111fbc3bf24db7fdb8e0 “Make Hitch backend-UDS capable” introduces support for domain sockets.

**Comment by Dridi** [comment]
@alexshpilkin, sorry for the late response, I found this in my github inbox. The latest hitch release has UDS support towards the backend!
