### ISSUE TITLE
Add support for multi-threading

### ISSUE THREAD

**Issue by p-id** [varnish/hitch#284]
Hitch service seems to work quite well in regards to a small memory footprint and ~200 KB of overhead per SSL connection/session.

However, in terms to performance is does fall short in comparison to some of the other projects (For example HAProxy). One of the way to resolve this particular issue is to switch to multi-threaded mode, which most of the applications like Envoy-Proxy and HAProxy have also adopted.

Reference: 
https://www.haproxy.com/blog/multithreading-in-haproxy/
https://blog.envoyproxy.io/envoy-threading-model-a8d44b922310

**Comment by steven-j-wojcik** [comment]
Hi,

I discussed this issue with the team in an internal meeting. After some research and load testing we found our performance vs other SSL termination tools that use multi-threading was equal. This is not apart of the features that we are actively working on now, but if new arguments comes up we may consider it at some point.

Steven

**Comment by MortenVinding** [comment]
Sorry for negro posting in the issue, but this bite me so hard I want to avoid the hassle for others:

Hitch does not support threading, it DOES however support multiple workers (processes), using the config option:
workers = <number, usually the same as CPU's>          (can be "auto" since v. 1.8)

This was necessary to bring site back online during a peak.
