### ISSUE TITLE
1.5.0: TLS1.3 isn't really default on since everyone has old openssl

### ISSUE THREAD

**Issue by lkarsten** [varnish/hitch#295]
The documentation (man-page) says:
```
   tls-protos = ...
       The  SSL/TLS  protocols  to  be  used. This is an unquoted list of tokens. Available tokens are SSLv3, TLSv1.0, TLSv1.1, TLSv1.2 and
       TLSv1.3.

       The default is TLSv1.2 and TLSv1.3.
```

I think this should be extended to mention that you need very recent openssl (1.1.1) as well.

On my Ubuntu Bionic system 1.1.0g-2ubuntu4.3 is installed, and hitch quietly only responds to TLS v1.2 now. 

Either something in the documentation or a startup notification to syslog if TLS 1.3 can't be found/enabled, would be very nice.

**Comment by lkarsten** [comment]
Related: it would seem that changing tls-protos to include TLS1.1, needs a full restart. Reload is not enough. I can't find this documented anywhere. I'm using the global tls-protos flag in hitch.conf on 1.5.0.

Seen when you upgrade from 1.4 to 1.5.0; TLS1.1 is disabled by default.

**Comment by dmatetelki** [comment]
I'll address the tls-proto: TLSv1.3 on a non OpenSSL-1.1.1 system with a check at:

https://github.com/varnish/hitch/pull/308/files#diff-f7bfb4ebcf98d5fde0b95a345ccfa85fR416

**Comment by dmatetelki** [comment]
@lkarsten : The doc says:

```
Issuing a SIGHUP signal to the main Hitch process will initiate a
reload of Hitch's configuration file.

Adding, updating and removing PEM files (``pem-file``) and frontend
listen endpoints (``frontend``) is currently supported.
```

So in my reading, these are the only things which are ok with a simple reload.
Do you think this should be extended to be more explicit ?

**Comment by daghf** [comment]
Added some notes in the docs on ``tls-protos`` and protocol availability.

https://github.com/varnish/hitch/commit/e51686b0a5daf7f3c45ba7b4810b89edb51cdb70

**Comment by bago** [comment]
I just installed 1.7.0 in el7 with openssl11 package from epel installed but sounds like TSLv1.3 doesn't work.

I don't know how to check from logs if the issue is openssl related: I simply checked with https://www.ssllabs.com/ssltest/ and they say we don't support 1.3.

Is tls 1.3 on Centos7 using hitch 1.7.0.el7 package supposed to work when openss11 package is installed? Should I open another issue?

I agree with this issue that when TLSv1.3 is enabled in the configuration but hitch is not able to support it (because of wrong openssl or similar) it would help something written in the startup logs (or even a failure to start).
