### ISSUE TITLE
Bad Domain with Non SAN/UCC Certificates

### ISSUE THREAD

**Issue by tuaris** [varnish/hitch#311]
I've noticed that if I use a "regular" certificate where the domain is listed in the CN and the certificate does not use any SANs I get a "Error code: SSL_ERROR_BAD_CERT_DOMAIN".  When using a certificate where I list the domain as a SAN, it work as expected.

I'm unsure if it's a configuration issue, or something I'm doing wrong with my non-SAN certs.  Before I go crazy trying to track that down... I figured I might as well ask the question:  Can I use non-SAN certificates with Hitch?

This is what my configuration looks like.  I'm using 1.5.0

```
frontend = "[*]:443"
backend = "[127.0.0.1]:8000"
ciphers = ""
prefer-server-ciphers = off
ssl-engine = ""
ocsp-dir = "/var/cache/hitch"
workers = 1
backlog = 100
keepalive = 3600
chroot = ""
user = "hitch"
group = "hitch"
quiet = off
syslog = on
syslog-facility = "daemon"
daemon = on
write-ip = off
write-proxy = off
write-proxy-v2 = on
proxy-proxy = off
pem-dir = "/usr/local/etc/cert.d/"
pem-dir-glob = "*.pem"
alpn-protos = "h2,http/1.1"
log-level = 2
```

Under `/usr/local/etc/cert.d/` I have the certificates in PEM format using KEY > CERT > CHAIN > $( openssl dhparam 2048)

**Comment by mphilipps** [comment]
Non SAN certificates are uncommon and likely to be not trusted by browsers. Why do you want to use a certificate without a SAN?

**Comment by michaelkennedy** [comment]
This is a browser issue, and certificates without SANs are no longer deemed valid.

The current CA/Browser Forum Baseline Reqs. prohibit certificates without SubjectAlternateName ([see section 7.1.4.2.1](https://cabforum-travis-artifacts.s3-us-west-2.amazonaws.com/builds/master/BR.html#subject-alternative-name-extension)), and since [Chrome 58](https://support.google.com/chrome/a/answer/7391219?hl=en) only the SAN is used for certificate validation. Other browsers have similar requirements which.

**Comment by daghf** [comment]
I have nothing to add to what's already been stated on here re non-SAN certificates.

Closing.
